name: backfill from datasets

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write  # Grant write permissions to the repository contents
  issues: write    # Grant write permissions to create issues

jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the version of Python you need

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    
    - name: Run fill
      run: python backfill.py

    - name: Commit and Push Result
      id: git_commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided GITHUB_TOKEN
      run: |
        git add -A 
        git commit -m "backfill populated"
        git push
      continue-on-error: true
